"""GBA CARTRIDGE HEADER (STANDARD)

File offset: 0x000 – 0x0BF

This header is:
- Mandatory
- Validated by BIOS
- Required for execution

Many fields are informational, but some MUST match
exact expected values (logo, fixed value, checksum).
"""

from constants import ByteOrder, Encoding, Kind, Origin, Tag
from core.bytes_region import BytesLayout, BytesRegion, MappedDefaultValue

__all__ = ["GBA_HEADER_LAYOUT"]


GBA_HEADER_LAYOUT = BytesLayout(
    id="gba.header.standard",
    name="GBA Cartridge Header",
    origin=Origin.spec,
    confidence=1.0,
    canonical_offset=0x000,
    address_space="gba.rom",
    tags=[Tag.structural],
    notes="Standard fixed GBA cartridge header.",
    provides=["header", "identity", "cartridge_metadata"],
    requires=["gba.vectors.standard"],
    excludes=None,
    applies_to=None,
    replaces=None,
    regions=[
        BytesRegion(
            id="gba.header",
            address_space="gba.rom",
            name="GBA Cartridge Header",
            byte_order=ByteOrder.little,
            kind=Kind.header,
            origin=Origin.spec,
            confidence=1.0,
            offset=0x000,
            size=0xC0,
            required=True,
            tags=[Tag.structural],
            notes="Standard fixed GBA cartridge header located at the beginning of the ROM.",
        ),
        BytesRegion(
            id="gba.header.entry_point",
            address_space="gba.rom",
            name="ROM Entry Point",
            kind=Kind.code,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x000,
            size=4,
            required=True,
            tags=[Tag.execution, Tag.validation],
            notes="32-bit ARM branch instruction",
        ),
        BytesRegion(
            id="gba.header.nintendo_logo",
            address_space="gba.rom",
            name="Nintendo Logo",
            kind=Kind.reserved,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x004,
            size=156,
            required=True,
            tags=[Tag.validation],
            notes="Compressed bitmap, must match official logo",
        ),
        BytesRegion(
            id="gba.header.game_title",
            address_space="gba.rom",
            name="Game Title",
            kind=Kind.text,
            origin=Origin.spec,
            encoding=Encoding.ascii,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0A0,
            size=12,
            required=True,
            tags=[Tag.informational],
        ),
        BytesRegion(
            id="gba.header.game_code",
            address_space="gba.rom",
            name="Game Code",
            kind=Kind.text,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            encoding=Encoding.ascii,
            confidence=1.0,
            offset=0x0AC,
            size=4,
            required=True,
            tags=[Tag.informational, Tag.structural],
        ),
        BytesRegion(
            id="gba.header.game_code.unique",
            address_space="gba.rom",
            name="Game Code – Unique ID",
            kind=Kind.text,
            origin=Origin.spec,
            encoding=Encoding.ascii,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0AC,
            size=1,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"A",
                    meaning="Normal game; Older titles (mainly 2001..2003)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.a",
                ),
                MappedDefaultValue(
                    raw=b"B",
                    meaning="Normal game; Newer titles (2003..)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.b",
                ),
                MappedDefaultValue(
                    raw=b"C",
                    meaning="Normal game; Not used yet, but might be used for even newer titles",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.c",
                ),
                MappedDefaultValue(
                    raw=b"F",
                    meaning="Famicom/Classic NES Series (software emulated NES games)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.f",
                ),
                MappedDefaultValue(
                    raw=b"K",
                    meaning="Yoshi and Koro Koro Puzzle (acceleration sensor)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.k",
                ),
                MappedDefaultValue(
                    raw=b"P",
                    meaning="e-Reader (dot-code scanner) (or NDS PassMe image when gamecode='PASS')",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.p",
                ),
                MappedDefaultValue(
                    raw=b"R",
                    meaning="Warioware Twisted (cartridge with rumble and z-axis gyro sensor)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.r",
                ),
                MappedDefaultValue(
                    raw=b"U",
                    meaning="Boktai 1 and 2 (cartridge with RTC and solar sensor)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.u",
                ),
                MappedDefaultValue(
                    raw=b"V",
                    meaning="Drill Dozer (cartridge with rumble)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.unique.v",
                ),
            ],
            tags=[Tag.informational, Tag.structural],
        ),
        BytesRegion(
            id="gba.header.game_code.short_title",
            address_space="gba.rom",
            name="Game Code – Short Title",
            kind=Kind.text,
            origin=Origin.spec,
            encoding=Encoding.ascii,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0AD,
            size=2,
            required=True,
            tags=[Tag.informational],
        ),
        BytesRegion(
            id="gba.header.game_code.region",
            address_space="gba.rom",
            name="Game Code – Region",
            kind=Kind.text,
            origin=Origin.spec,
            encoding=Encoding.ascii,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0AF,
            size=1,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"J",
                    meaning="Japan",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.j",
                ),
                MappedDefaultValue(
                    raw=b"E",
                    meaning="USA/English",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.e",
                ),
                MappedDefaultValue(
                    raw=b"P",
                    meaning="Europe/Elsewhere",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.p",
                ),
                MappedDefaultValue(
                    raw=b"D",
                    meaning="German",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.d",
                ),
                MappedDefaultValue(
                    raw=b"F",
                    meaning="French",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.f",
                ),
                MappedDefaultValue(
                    raw=b"I",
                    meaning="Italian",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.i",
                ),
                MappedDefaultValue(
                    raw=b"S",
                    meaning="Spanish",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.game_code.region.s",
                ),
            ],
            tags=[Tag.informational],
        ),
        BytesRegion(
            id="gba.header.maker_code",
            address_space="gba.rom",
            name="Maker Code",
            kind=Kind.text,
            origin=Origin.spec,
            encoding=Encoding.ascii,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0B0,
            size=2,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"01",
                    meaning="Nintendo",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.maker_code.nintendo",
                ),
                MappedDefaultValue(
                    raw=b"08",
                    meaning="Capcom",
                    origin=Origin.observed,
                    confidence=0.95,
                    id="gba.header.maker_code.capcom",
                ),
                MappedDefaultValue(
                    raw=b"13",
                    meaning="Electronic Arts",
                    origin=Origin.observed,
                    confidence=0.95,
                    id="gba.header.maker_code.ea",
                ),
                MappedDefaultValue(
                    raw=b"18",
                    meaning="Hudson Soft",
                    origin=Origin.observed,
                    confidence=0.9,
                    id="gba.header.maker_code.hudson",
                ),
                MappedDefaultValue(
                    raw=b"28",
                    meaning="Kemco",
                    origin=Origin.observed,
                    confidence=0.9,
                    id="gba.header.maker_code.kemco",
                ),
                MappedDefaultValue(
                    raw=b"32",
                    meaning="Bandai",
                    origin=Origin.observed,
                    confidence=0.95,
                    id="gba.header.maker_code.bandai",
                ),
                MappedDefaultValue(
                    raw=b"34",
                    meaning="Konami",
                    origin=Origin.observed,
                    confidence=0.95,
                    id="gba.header.maker_code.konami",
                ),
                MappedDefaultValue(
                    raw=b"41",
                    meaning="Ubisoft",
                    origin=Origin.observed,
                    confidence=0.9,
                    id="gba.header.maker_code.ubisoft",
                ),
                MappedDefaultValue(
                    raw=b"49",
                    meaning="Irem",
                    origin=Origin.observed,
                    confidence=0.85,
                    id="gba.header.maker_code.irem",
                ),
                MappedDefaultValue(
                    raw=b"50",
                    meaning="Absolute Entertainment",
                    origin=Origin.observed,
                    confidence=0.85,
                    id="gba.header.maker_code.absolute",
                ),
                MappedDefaultValue(
                    raw=b"52",
                    meaning="Activision",
                    origin=Origin.observed,
                    confidence=0.95,
                    id="gba.header.maker_code.activision",
                ),
                MappedDefaultValue(
                    raw=b"60",
                    meaning="Titus",
                    origin=Origin.observed,
                    confidence=0.85,
                    id="gba.header.maker_code.titus",
                ),
                MappedDefaultValue(
                    raw=b"64",
                    meaning="LucasArts",
                    origin=Origin.observed,
                    confidence=0.9,
                    id="gba.header.maker_code.lucasarts",
                ),
                MappedDefaultValue(
                    raw=b"70",
                    meaning="Infogrames",
                    origin=Origin.observed,
                    confidence=0.9,
                    id="gba.header.maker_code.infogrames",
                ),
            ],
            tags=[Tag.informational],
        ),
        BytesRegion(
            id="gba.header.fixed_value",
            address_space="gba.rom",
            name="Fixed Value (0x96)",
            kind=Kind.reserved,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0B2,
            size=1,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x96",
                    meaning="Must be 0x96",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.fixed_value.0x96",
                ),
            ],
            tags=[Tag.validation],
        ),
        BytesRegion(
            id="gba.header.main_unit_code",
            address_space="gba.rom",
            name="Main Unit Code",
            kind=Kind.data,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0B3,
            size=1,
            required=True,
            notes="00h for standard GBA",
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x00",
                    meaning="00h for current GBA models",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.main_unit_code.0x00",
                ),
            ],
            tags=[Tag.validation, Tag.structural],
        ),
        BytesRegion(
            id="gba.header.device_type",
            address_space="gba.rom",
            name="Device Type",
            kind=Kind.data,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0B4,
            size=1,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x00",
                    meaning="Normal device type (usual default)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.device_type.normal",
                )
            ],
            tags=[Tag.validation],
        ),
        BytesRegion(
            id="gba.header.reserved_1",
            address_space="gba.rom",
            name="Reserved Area",
            kind=Kind.reserved,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0B5,
            size=7,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x00" * 7,
                    meaning="Should be zero-filled",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.reserved_1.zero_filled",
                )
            ],
            tags=[Tag.validation, Tag.deprecated],
        ),
        BytesRegion(
            id="gba.header.software_version",
            address_space="gba.rom",
            name="Software Version",
            kind=Kind.data,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0BC,
            size=1,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x00",
                    meaning="Usually zero (software version)",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.software_version.zero",
                )
            ],
            tags=[Tag.informational],
        ),
        BytesRegion(
            id="gba.header.checksum",
            address_space="gba.rom",
            name="Header Checksum",
            kind=Kind.data,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0BD,
            size=1,
            required=True,
            tags=[Tag.validation],
            notes="Complement check of bytes 0xA0–0xBC",
        ),
        BytesRegion(
            id="gba.header.reserved_2",
            address_space="gba.rom",
            name="Reserved Area",
            kind=Kind.reserved,
            origin=Origin.spec,
            byte_order=ByteOrder.little,
            confidence=1.0,
            offset=0x0BE,
            size=2,
            required=True,
            default_value_mapped=[
                MappedDefaultValue(
                    raw=b"\x00" * 2,
                    meaning="Should be zero-filled",
                    origin=Origin.spec,
                    confidence=1.0,
                    id="gba.header.reserved_2.zero_filled",
                )
            ],
            Tags=[Tag.validation, Tag.deprecated],
        ),
    ],
)
