"""fix_translation_job

Revision ID: 343ae8349f23
Revises: 97dec4f59146
Create Date: 2025-04-25 22:30:42.313153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343ae8349f23'
down_revision = '97dec4f59146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
