"""fix_translation_job_created_at

Revision ID: 97dec4f59146
Revises: 5380b828f70c
Create Date: 2025-04-25 22:27:13.827558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dec4f59146'
down_revision = '5380b828f70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
